[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
    4-20ma/ModbusMaster@^2.0.1
    adafruit/Adafruit GFX Library@^1.11.11
    adafruit/Adafruit ILI9341@^1.6.2
    tzapu/WiFiManager@^2.0.17

